[package]
name = "open"
version = "0.1.0"
authors = ["Britton Wolfe <britton.wolfe1999@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
configparser = "2.0.1"
